Проверка на простоту
OnlyDeniko/QuantumComputingCourse pull request #1
Opened 2021-10-30 18:47 UTC by Rethinking-1

Cmake работает нормально?В txtfiles 3 файла с числами кармайкла по заданию,3 с выходными данными(ферма,рабин-миллер),1 файл с выходными данными первых 100к чисел

2021-10-30 21:52 UTC, Rethinking-1 commented
Вроде как исправил.

2021-10-31 10:16 UTC, Rethinking-1 commented
.

2021-10-31 12:44 UTC, Rethinking-1 commented
В общем я не знаю в чём проблема. Пробовал собрать проект по cmake из примера,у меня проект не собрался.
![4](https://user-images.githubusercontent.com/56755273/139583783-a5caf643-45a4-43a4-8bf7-40a7f90fb79e.jpg)

[
![1](https://user-images.githubusercontent.com/56755273/139583714-e4dc0e31-d198-451a-8a13-c01d821d149e.jpg)
![2](https://user-images.githubusercontent.com/56755273/139583717-bc16cd2c-138b-4fbb-bc98-9a58464fe263.jpg)
![3](https://user-images.githubusercontent.com/56755273/139583719-bdf43b8a-913f-40c2-88c2-799ab6d00131.jpg)
](url)

2021-10-31 13:03 UTC, OnlyDeniko commented
> В общем я не знаю в чём проблема. Пробовал собрать проект по cmake из примера,у меня проект не собрался. ![4](https://user-images.githubusercontent.com/56755273/139583783-a5caf643-45a4-43a4-8bf7-40a7f90fb79e.jpg)
> 
> [ ![1](https://user-images.githubusercontent.com/56755273/139583714-e4dc0e31-d198-451a-8a13-c01d821d149e.jpg) ![2](https://user-images.githubusercontent.com/56755273/139583717-bc16cd2c-138b-4fbb-bc98-9a58464fe263.jpg) ![3](https://user-images.githubusercontent.com/56755273/139583719-bdf43b8a-913f-40c2-88c2-799ab6d00131.jpg) ](url)

Собирать необходимо весь проект и не в MCVS, а в терминале/командной строке. Гайд по запуску написан в readme

2021-10-31 13:06 UTC, Rethinking-1 commented
Я и собираю в командной стоке. Через git bash собирал и через обычную консоль. Это просто скрины,что после попытки сборки

2021-10-31 13:09 UTC, OnlyDeniko commented
> Я и собираю в командной стоке. Через git bash собирал и через обычную консоль. Это просто скрины,что после попытки сборки

Сделайте CMakeLists.txt как в [примере](https://github.com/OnlyDeniko/QuantumComputingCourse/blob/main/modules/task1_prime_numbers/kulandin_d/CMakeLists.txt)

2021-10-31 13:17 UTC, Rethinking-1 commented
![1](https://user-images.githubusercontent.com/56755273/139585390-7ed86eca-4c26-4a41-8b97-56bf24e15ddb.jpg)

2021-10-31 13:20 UTC, OnlyDeniko commented
Внимательно прочитайте гайд по запуску. Папку build нужно создавать в корне репозитория

2021-10-31 13:33 UTC, Rethinking-1 commented
Да,так собрался

2021-10-31 13:36 UTC, Rethinking-1 commented
Когда последний раз запушил,там как раз заменил CmakeLists.txt как в примере.

2021-10-31 13:38 UTC, OnlyDeniko commented
> Когда последний раз запушил,там как раз заменил CmakeLists.txt как в примере.

Файл должен называться CMakeLists.txt

2021-10-31 13:50 UTC, Rethinking-1 commented
Поменял

2021-10-31 13:58 UTC, Rethinking-1 commented
В чём проблема?Я не понимаю..

2021-10-31 14:16 UTC, OnlyDeniko commented
> В чём проблема?Я не понимаю..

Лог тестирования посмотри, там всё написано

2021-10-31 14:17 UTC, Rethinking-1 commented
Посмотрел. Исправить то это как?

2021-10-31 14:26 UTC, OnlyDeniko commented
> Посмотрел. Исправить то это как?

Написано же, переменная end1 нигде не используется

2021-10-31 14:38 UTC, Rethinking-1 commented
Ахах.С почином

2021-10-31 14:42 UTC, OnlyDeniko commented
> Ахах.С почином

В следующие разы смотреть пул реквест не буду, пока не пройдут все тесты. Исправить ошибки компиляции Вы вполне можете сами

2021-10-31 14:43 UTC, Rethinking-1 commented
Хорошо,спасибо. Согласен,косяк идиотский

2021-10-31 17:11 UTC, OnlyDeniko requested changes
Зачем тут файл на 100.000 строчек?

2021-10-31 17:11 UTC, OnlyDeniko commented on modules/task1_prime_numbers/Denisov_D/Operation.h
> +}
Рекурсия здесь ни к чему. Попробуйте от нее избавиться

2021-10-31 17:11 UTC, OnlyDeniko commented on modules/task1_prime_numbers/Denisov_D/Operation.h
> +  }
Свап тут не нужен

2021-10-31 17:11 UTC, OnlyDeniko commented on modules/task1_prime_numbers/Denisov_D/Operation.h
> +      z %= N;
Почему бы не просто ```z %= N``` без всяких условий?

2021-10-31 17:11 UTC, OnlyDeniko commented on modules/task1_prime_numbers/Denisov_D/Operation.h
> +    else if ((mod_pow(temp, number-1, number)) % number !=1)
При вызове ```mod_pow``` подразумевается, что полученный ответ уже будет корректным по модулю ```number```, поэтому операция взятия по модулю здесь лишняя

2021-10-31 17:11 UTC, OnlyDeniko commented on modules/task1_prime_numbers/Denisov_D/Operation.h
> +  ll counter = 0, attempts = 3;
Зачем этим переменным тип ```ll``` ? Достаточно просто ```int```

2021-10-31 17:11 UTC, OnlyDeniko commented on modules/task1_prime_numbers/Denisov_D/Operation.h
> +  ll tryes = 25, alpha = number - 1;
Почему именно 25? И снова для ```tries``` достаточно ```int```

2021-10-31 17:11 UTC, OnlyDeniko commented on modules/task1_prime_numbers/Denisov_D/Operation.h
> +    alpha *= 0.5;
Все операции у нас происходят с целыми числами, поэтому использование вещественных излишне. Почему бы не просто ```alpha /= 2``` или ```alpha >>= 1``` ?

2021-10-31 17:11 UTC, OnlyDeniko commented on modules/task1_prime_numbers/Denisov_D/Operation.h
> +  for (ll i = 0; i < tryes; i++)
```int i```

2021-10-31 17:11 UTC, OnlyDeniko commented on modules/task1_prime_numbers/Denisov_D/Operation.h
> +    ll temp = rand() % (number - 3) + 2;
```rand()``` генерирует числа лишь до ```32768```, в нашем случае нужны числа побольше. Попробуйте использовать генератор ```std::mt19937```, либо можно просто ```(rand() << 15) + rand()```

2021-10-31 17:11 UTC, OnlyDeniko commented on modules/task1_prime_numbers/Denisov_D/Operation.h
> +#pragma once
Как правило файл с расширением ```.h``` используется для реализации заголовков функций или для шаблонных реализаций функций. Поэтому добавьте ```.cpp```, а здесь оставьте только заголовки

2021-10-31 21:23 UTC, Rethinking-1 commented on modules/task1_prime_numbers/Denisov_D/Operation.h
> +#pragma once
+

2021-11-01 16:15 UTC, Rethinking-1 commented on modules/task1_prime_numbers/Denisov_D/Operation.h
> +  }
+

2021-11-01 16:15 UTC, Rethinking-1 commented on modules/task1_prime_numbers/Denisov_D/Operation.h
> +      z %= N;
+

2021-11-01 16:15 UTC, Rethinking-1 commented on modules/task1_prime_numbers/Denisov_D/Operation.h
> +    else if ((mod_pow(temp, number-1, number)) % number !=1)
+

2021-11-01 16:15 UTC, Rethinking-1 commented on modules/task1_prime_numbers/Denisov_D/Operation.h
> +  ll counter = 0, attempts = 3;
+

2021-11-01 16:16 UTC, Rethinking-1 commented on modules/task1_prime_numbers/Denisov_D/Operation.h
> +  ll tryes = 25, alpha = number - 1;
+

2021-11-01 16:16 UTC, Rethinking-1 commented on modules/task1_prime_numbers/Denisov_D/Operation.h
> +    alpha *= 0.5;
+

2021-11-01 16:16 UTC, Rethinking-1 commented on modules/task1_prime_numbers/Denisov_D/Operation.h
> +  for (ll i = 0; i < tryes; i++)
+

2021-11-01 16:16 UTC, Rethinking-1 commented on modules/task1_prime_numbers/Denisov_D/Operation.h
> +#pragma once
+

2021-11-02 07:05 UTC, OnlyDeniko commented on modules/task1_prime_numbers/Denisov_D/Operation.cpp
> + /* ll temp_x = 1, ans = y, save_y = y;//works much longer
Как может рекурсивное решение работать быстрее решения без рекурсии? Может быть вы неправильно реализовали...

2021-11-02 12:42 UTC, OnlyDeniko commented on modules/task1_prime_numbers/Denisov_D/Operation.cpp
> +ll mod_pow(ll x, ll y, ll N)
Да, реализация бинарного умножения по модулю похожа на правду. Теперь нужно поправить бинарное возведение в степень (избавиться от рекурсии)

2021-11-02 13:02 UTC, Rethinking-1 commented on modules/task1_prime_numbers/Denisov_D/Operation.cpp
> +ll mod_pow(ll x, ll y, ll N)
Ну вот это бинарное умножение работает в 2 раза дольше,чем было до этого.

2021-11-02 13:11 UTC, Rethinking-1 commented on modules/task1_prime_numbers/Denisov_D/Operation.cpp
> +ll mod_pow(ll x, ll y, ll N)
Щас закину бинарное возведение

2021-11-02 13:57 UTC, OnlyDeniko commented on modules/task1_prime_numbers/Denisov_D/Operation.cpp
> +ll mod_pow(ll x, ll y, ll N)
Напиши аналогично как бинарное произведение, эта реализация, конечно, будет работать долго

2021-11-02 20:58 UTC, Rethinking-1 commented
В общем,я создал data.cpp,там все мои свои идеи написал по поводу других реализаций. Всё из того работает медленнее,чем в последнем пуше(back). Посмотрел реализацию Faert,оно тоже не ускорило мою реализацию.

2021-11-03 06:37 UTC, OnlyDeniko commented
Корректная реализация не рекурсивного бинарного возведения в степень:
```
int mod_pow(int a, int b, int mod){
  int ans = 1;
  while(b){
    if (b & 1){
      ans = Mult(ans, a);
    }
    b >>= 1;
    a = Mult(a, a);
  }
  return ans;
}
```

2021-11-03 08:22 UTC, Rethinking-1 commented
Переделал

2021-11-03 08:34 UTC, OnlyDeniko approved these changes

2021-11-03 08:35 UTC, merged